### ISSUE TITLE
TUF H370-Pro Gaming  8400

### ISSUE THREAD

**Issue by stonexing** [TCattd/Hackintosh-ASUS-TUF-H370-PRO#1]
Board: ASUS TUF H370-Pro Gaming
 CPU: Intel Core i5-8400 
I have no wifi, no AMD Graphics, no NVME ssd
Can not success
I use your EFI Got  this error:
![IMG_0958](https://user-images.githubusercontent.com/1814765/68388618-0e05ab80-019c-11ea-8c0f-839c3e4556fc.JPG)
Then I fix ACPI error flowing: https://www.youtube.com/watch?v=IGTaTfjoBaY
remove _SB.PCI0.RP04.PXSX, _SB.PCI0.RP05.PXSX, _SB.PCI0.RP08.PXSX, _SB.PCI0.RP09.PXSX, and fix error
Then I got
![IMG_0959](https://user-images.githubusercontent.com/1814765/68389332-a6e8f680-019d-11ea-930e-3c2b30067ca7.JPG)
 
Can you help me?

**Comment by TCattd** [comment]
Those errors are during install?

Can see the error on the second picture. Too blurry.

**Comment by stonexing** [comment]
Hi TCattd！
Thank you for response；
I see you update EFI for usb install
I'm install 10.15.1 now
I use your UEFIBIOS_20190904A.CMO for my bios
1:I can not boot success for install macOS Catalina from USB;
2:I use "EFI-20190522-USB-Install-Minimal" as the EFI can not find "macOS" disk under clover, (can only see windows under EFI, no macOS, and this seems 20190522 must be use old clover not support Catalina)

Can you upload a new EFI support "macOS Catalina install USB" ?
Many thanks for TCattd!

**Comment by TCattd** [comment]
@stonexing in fact, i did install macOS Catalina with the EFI folder in the repo's root. The main EFI folder. The Vanilla one.

When this happened https://github.com/TCattd/Hackintosh-ASUS-TUF-H370-PRO#2019-10-30 i tested it updating and then wiping the drive and installing from scratch (with and USB Installer). Restored my data from a Time Machine Backup.

Did it just to test my folder properly. And works.

Take into consideration that my computer has a discrete video card installed, and two drives (sata and nvme).

I did update Clover on the old EFI Install Minimal. Is has the same version as the main EFI folder. Even updated it to use the same new folder order that Clover expect.
Both, main EFI folder and Minimal Install, use Clover 5093.

I'm not expert about this Hackintosh thing anyways. Keep that in mind. Took me a lot of trial and error to get to a stable config for my rig.
Anyhow, without logs of your system hanging up, it's difficult to tell what can be wrong with your install.

**Comment by stonexing** [comment]
Thanks a lot TCattd
I have already install 10.15.1 success use your EFI with a little change of config.plist
1:I remove Devices->Properties-> PciRoot(0x0)/Pci(0x2,0x0)
2:and add Graphics -> Inject Intel -> ig-platform-id ->0x12345678 to disable intel graphics
With this I install success 
After install success, I do invert of step 1 and 2 to get intel UHD Graphics 630 works

Now：
wired-network works
Sound ALC887 works
Graphics UHD630 works
![WechatIMG60](https://user-images.githubusercontent.com/1814765/68639282-06992600-053f-11ea-8be4-4e4d0a9c0020.jpeg)

Many Thanks TCattd！

**Comment by TCattd** [comment]
Congratulations!
