### ISSUE TITLE
cannot make FaceTime and iMessage work, but apple store and iCloud are ok

### ISSUE THREAD

**Issue by bricco1981** [TCattd/Hackintosh-ASUS-TUF-H370-PRO#2]
hi, I cannot make work FaceTime and iCloud.
i have this motherboard, I don't have any wifi card, I don't have any graphic card, I use the integrated gpu in my intel i8700 k.
i even tried a real serial number one of my Mac not in use anymore.
I used your refi folder
any help please?

**Comment by TCattd** [comment]
The key is to use a card like the one i linked on the readme: Fenvi FV-T919 Broadcom BCM94360CD
Without one of those, it will never work.

Go to AliExpress and search for "hackintosh wifi". A lot of compatible chipset will pop up, like the BCM94360CD i use. Check for compatibility online for any other chipset.

**Comment by bricco1981** [comment]
so I cannot make it work with ethernet?

**Comment by TCattd** [comment]
I don't think so. Not only with it. You will still need the combo card (wifi + bluetooth).
After that, i presume that it should work with either wifi or ethernet, since the OS will detect the compatible card, it shouldn't matter after that point.

**Comment by bricco1981** [comment]
thanks very much the problem with this Broadcom are not good for linux, I have an alfa 1900, I m not sure if this will work?

**Comment by TCattd** [comment]
You will have better luck asking those questions at:  tonymacx86.com, hackintosher.com, insanelymac.com or hackintoshzone.com.

I'm not an expert on this Hackintosh thing.
This was my first build and try. I just searched and read a lot before jumping in.

**Comment by bricco1981** [comment]
thanks ,you have done a great job on this build.

**Comment by TCattd** [comment]
Thank you. Have a nice day!

**Comment by bricco1981** [comment]
hallo, hope all is well, I made it working. so finally I made it working,  if you want add the solution next build please..... the solution is install emuvariableuefi 
have a good one

**Comment by TCattd** [comment]
Where did you got that file?
Can you link it here, please?, to test it.
Thanks.

**Comment by bricco1981** [comment]
I just opened your efi folder with clover configurator. 
just open config.plist and click on install software, find emuvariableefi and install it.
also now I'm trying to understand why the aura, led are not working, I have a tempered glass case, so the led are nice to have.

**Comment by TCattd** [comment]
Tested and did not harm anything, so, i added it to my folder.

https://github.com/TCattd/Hackintosh-ASUS-TUF-H370-PRO/commit/85976bfb7b9b608417a0cd8d2f012b352dea082a

Thank you @bricco1981 

Good to know about the wifi card :)
Good luck with the leds.

**Comment by bricco1981** [comment]
fixed led rib : this is more user needs, anyway to make it work in bios setting erp ready should be disable.
