### ISSUE TITLE
cannot boot

### ISSUE THREAD

**Issue by bricco1981** [TCattd/Hackintosh-ASUS-TUF-H370-PRO#3]
hi, I cannot boot the usb with last  catalina , your config.plist is empty, could be that? new to OpenCore.

**Comment by TCattd** [comment]
The config plist in this repo is not empty, @bricco1981 
Check it out: https://tppr.me/XT3X8

Make sure to download the repo as zip (if you don't want to clone it): https://tppr.me/b51yO and use the EFI folder.

Esteban

**Comment by bricco1981** [comment]
i have no idea, the installer is made on original Mac, and boot, but no clover or oc efi is working on the pc.

**Comment by bricco1981** [comment]
can confirm that you can boot last catalina from usb?

**Comment by TCattd** [comment]
Of course i can.

Check your EFI folder. That "your config.plist is empty" doesn't seems right.

**Comment by bricco1981** [comment]
sorry, i was usin clover config and the file had less info compared to clover .plist.
at this point i don't know why i cannot boot.
opencore need just the efi folder in the efi partition of the usb? 
should i change someting in your efi before i can boot from the usb?

**Comment by TCattd** [comment]
@bricco1981 you should really read the guide from dortania https://dortania.github.io/OpenCore-Install-Guide/ carefully. Take your time.

Then, **if you have the same motherboard, processor, external video card and wifi card**, then your build should boot with my EFI folder just fine.
If not, if some of your hardware if different from mine, you need to make the appropriated changes to your OpenCore config file.

Again, dortania's guide explains the whole process pretty well.

Esteban

**Comment by bricco1981** [comment]
thanks, now i see, mabie the difference is that i have an ssd.

**Comment by TCattd** [comment]
SSD should not make it not to boot.
I don't remember anything about them in OpenCore in particular.

You mentioned a different GPU. That's probably your issue here.

**Comment by bricco1981** [comment]
very strange ,motherboard is the same, cpu is the same, yes i have the rtx but it's like i don't use it in mac os, the hdmi is plugged into the mobo.
that's why i asked if i need like  the gpu

**Comment by TCattd** [comment]
Using just the internal GPU (Intel) will need changes to OpenCore's config.

Check Dortania's guide, please.
