### ISSUE TITLE
Can not use for my Asus TUF H370 Pro

### ISSUE THREAD

**Issue by stonexing** [TCattd/Hackintosh-ASUS-TUF-H370-PRO#4]
I find the config.plist under OC is empty
Can you give out you config with out platform info

**Comment by TCattd** [comment]
What?

config.plist isn't empty.

https://github.com/TCattd/Hackintosh-ASUS-TUF-H370-PRO/blob/master/EFI/OC/config.plist it's populated.

Screenshot: https://tppr.me/3YBLK

If you don't clone the repo locally to your computer, then make sure to download the repo as zip: https://tppr.me/MP3IA

Esteban
